import { ICuota } from "types-prestamista";


export const cuotas: ICuota[] = [
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-03-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-04-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-05-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-06-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-07-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-08-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-09-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-10-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-11-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2023-12-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2024-01-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2024-02-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2024-03-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2024-04-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
    {
        cliente: null as any,
        agente: null as any,
        fechaPago: new Date('2024-05-10'),
        monto: 150,
        prestamo: null as any,
        fechaLimite: new Date('2023-03-10'),
    },
]