import { ICliente } from "types-prestamista";

export const clientes: ICliente[] = [
    {
        documento: "12345678",
        nombres: "Juan Pedro",
        apellidos: "García Pérez",
        genero: "Masculino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 1",
        ruc: "12345678901",
        razonSocial: "Razón Social 1",
        estado: "Activo",
        correo: "juanpedrogarcia@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
    {
        documento: "23456789",
        nombres: "Ana María",
        apellidos: "Rodríguez Torres",
        genero: "Femenino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 2",
        ruc: "12345678901",
        razonSocial: "Razón Social 2",
        estado: "Activo",
        correo: "anamariarodriguez@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
    {
        documento: "34567890",
        nombres: "Carlos Eduardo",
        apellidos: "López Vásquez",
        genero: "Masculino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 3",
        ruc: "12345678901",
        razonSocial: "Razón Social 3",
        estado: "Inactivo",
        correo: "carloseduardolopez@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
    {
        documento: "45678901",
        nombres: "María Fernanda",
        apellidos: "García Pérez",
        genero: "Femenino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 4",
        ruc: "12345678901",
        razonSocial: "Razón Social 4",
        estado: "Activo",
        correo: "mariafernandagarcia@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
    {
        documento: "56789012",
        nombres: "Luis Alberto",
        apellidos: "Martínez López",
        genero: "Masculino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 5",
        ruc: "12345678901",
        razonSocial: "Razón Social 5",
        estado: "Inactivo",
        correo: "luisalbertomartinez@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
    {
        documento: "67890123",
        nombres: "Carmen Rosa",
        apellidos: "Fernández Castillo",
        genero: "Femenino",
        celular: "987654321",
        telefono: "1234567",
        empresa: "Empresa 6",
        ruc: "12345678901",
        razonSocial: "Razón Social 6",
        estado: "Activo",
        correo: "carmenrosafernandez@gmail.com",
        agente: null as any,
        direccion: null as any,
    },
];