import { IPrestamo } from "types-prestamista";

export const prestamos: IPrestamo[] = [
    {
        numero: 1,
        cliente: null as any,
        monto: 1000,
        interes: 0.5,
        montoTotal: 1500,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 12,
        formaPago: 'MENSUAL',
    },
    {
        numero: 2,
        cliente: null as any,
        monto: 2000,
        interes: 0.8,
        montoTotal: 2400,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 6,
        formaPago: 'DIARIO',
    },
    {
        numero: 3,
        cliente: null as any,
        monto: 5000,
        interes: 0.7,
        montoTotal: 6350,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 10,
        formaPago: 'MENSUAL',
    },
    {
        numero: 4,
        cliente: null as any,
        monto: 3000,
        interes: 1,
        montoTotal: 4500,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 12,
        formaPago: 'QUINCENAL',
    },
    {
        numero: 5,
        cliente: null as any,
        monto: 1500,
        interes: 0.6,
        montoTotal: 1950,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 8,
        formaPago: 'MENSUAL',
    },
    {
        numero: 6,
        cliente: null as any,
        monto: 8000,
        interes: 0.9,
        montoTotal: 10400,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 12,
        formaPago: 'MENSUAL',
    },
    {
        numero: 7,
        cliente: null as any,
        monto: 4000,
        interes: 0.7,
        montoTotal: 5080,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 10,
        formaPago: 'SEMANAL',
    },
    {
        numero: 8,
        cliente: null as any,
        monto: 10000,
        interes: 0.8,
        montoTotal: 12000,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 6,
        formaPago: 'MENSUAL',
    },
    {
        numero: 10,
        cliente: null as any,
        monto: 1500,
        interes: 0.7,
        montoTotal: 1905,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 9,
        formaPago: 'MENSUAL',
    },
    {
        numero: 11,
        cliente: null as any,
        monto: 8000,
        interes: 0.9,
        montoTotal: 10400,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 12,
        formaPago: 'MENSUAL',
    },
    {
        numero: 12,
        cliente: null as any,
        monto: 4000,
        interes: 0.8,
        montoTotal: 4800,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 6,
        formaPago: 'MENSUAL',
    },
    {
        numero: 13,
        cliente: null as any,
        monto: 10000,
        interes: 1.2,
        montoTotal: 13000,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 12,
        formaPago: 'MENSUAL',
    },
    {
        numero: 14,
        cliente: null as any,
        monto: 3000,
        interes: 0.5,
        montoTotal: 3750,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 15,
        formaPago: 'DIARIO',
    },
    {
        numero: 15,
        cliente: null as any,
        monto: 6000,
        interes: 0.7,
        montoTotal: 7620,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 18,
        formaPago: 'MENSUAL',
    },
    {
        numero: 16,
        cliente: null as any,
        monto: 2000,
        interes: 0.9,
        montoTotal: 2600,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 10,
        formaPago: 'MENSUAL',
    },
    {
        numero: 17,
        cliente: null as any,
        monto: 7000,
        interes: 1,
        montoTotal: 10500,
        moneda: null as any,
        estado: 'Pendiente',
        agente: null as any,
        numeroCuotas: 15,
        formaPago: 'QUINCENAL',
    },
];