import { IDireccion } from "types-prestamista"

export const departamentos = [
  { uuid: 1, nombre: 'Amazonas' },
  { uuid: 2, nombre: 'Ancash' },
  { uuid: 3, nombre: 'Apurímac' },
  { uuid: 4, nombre: 'Arequipa' },
  { uuid: 5, nombre: 'Ayacucho' },
  { uuid: 6, nombre: 'Cajamarca' },
  { uuid: 7, nombre: 'Callao' },
  { uuid: 8, nombre: 'Cusco' },
  { uuid: 9, nombre: 'Huancavelica' },
  { uuid: 10, nombre: 'Huánuco' },
  { uuid: 11, nombre: 'Ica' },
  { uuid: 12, nombre: 'Junín' },
  { uuid: 13, nombre: 'La Libertad' },
  { uuid: 14, nombre: 'Lambayeque' },
  { uuid: 15, nombre: 'lima' },
  { uuid: 16, nombre: 'Loreto' },
  { uuid: 17, nombre: 'Madre de Dios' },
  { uuid: 18, nombre: 'Moquegua' },
  { uuid: 19, nombre: 'Pasco' },
  { uuid: 20, nombre: 'Piura' },
  { uuid: 21, nombre: 'Puno' },
  { uuid: 22, nombre: 'San Martín' },
  { uuid: 23, nombre: 'Tacna' },
  { uuid: 24, nombre: 'Tumbes' },
  { uuid: 25, nombre: 'Ucayali' }
]

export const provincias = [
  { uuid: 1, nombre: 'Bagua', departamento: 1 },
  { uuid: 2, nombre: 'Bongará', departamento: 1 },
  { uuid: 3, nombre: 'Chachapoyas', departamento: 1 },
  { uuid: 4, nombre: 'Condorcanqui', departamento: 1 },
  { uuid: 5, nombre: 'Luya', departamento: 1 },
  { uuid: 6, nombre: 'Rodríguez de Mendoza', departamento: 1 },
  { uuid: 7, nombre: 'Utcubamba', departamento: 1 },
  //
  { uuid: 8, nombre: 'Chanchamayo', departamento: 12 },
  { uuid: 9, nombre: 'Chupaca', departamento: 12 },
  { uuid: 10, nombre: 'Concepción', departamento: 12 },
  { uuid: 11, nombre: 'Huancayo', departamento: 12 },
  { uuid: 12, nombre: 'Jauja', departamento: 12 },
  { uuid: 13, nombre: 'Junín', departamento: 12 },
  { uuid: 14, nombre: 'Satipo', departamento: 12 },
  { uuid: 15, nombre: 'Tarma', departamento: 12 },
  { uuid: 16, nombre: 'Yauli', departamento: 12 }
]

export const distritos = [
  { uuid: 1, nombre: 'Aramango', provincia: 1 },
  { uuid: 2, nombre: 'Bagua', provincia: 1 },
  { uuid: 3, nombre: 'Copallín', provincia: 1 },
  { uuid: 4, nombre: 'El parco', provincia: 1 },
  { uuid: 5, nombre: 'Imaza', provincia: 1 },
  { uuid: 6, nombre: 'La peca', provincia: 1 },
  { uuid: 7, nombre: 'Shipasbamba', provincia: 1 },
  //
  { uuid: 8, nombre: 'Chisquilla', provincia: 2 },
  { uuid: 9, nombre: 'Churuja', provincia: 2 },
  { uuid: 10, nombre: 'Corocha', provincia: 2 },
  { uuid: 11, nombre: 'Cuispes', provincia: 2 },
  { uuid: 12, nombre: 'Florida', provincia: 2 },
  { uuid: 13, nombre: 'Jumbila', provincia: 2 },
  { uuid: 14, nombre: 'Pedro Ruiz Gallo', provincia: 2 },
  { uuid: 15, nombre: 'Recta', provincia: 2 },
  { uuid: 16, nombre: 'San Carlos', provincia: 2 },
  { uuid: 17, nombre: 'Shipasbamba', provincia: 2 },
  { uuid: 18, nombre: 'Valera', provincia: 2 },
  { uuid: 19, nombre: 'Yambrasbamba', provincia: 2 },
  //
  { uuid: 20, nombre: 'Asunción', provincia: 3 },
  { uuid: 21, nombre: 'Balsa', provincia: 3 },
  { uuid: 22, nombre: 'Chachapoyas', provincia: 3 },
  { uuid: 23, nombre: 'Cheto', provincia: 3 },
  { uuid: 24, nombre: 'Chiliquín', provincia: 3 },
  { uuid: 25, nombre: 'Chuquibamba', provincia: 3 },
  { uuid: 26, nombre: 'Granada', provincia: 3 },
  { uuid: 27, nombre: 'Huancas', provincia: 3 },
  { uuid: 28, nombre: 'La Jalca', provincia: 3 },
  { uuid: 29, nombre: 'Leimebamba', provincia: 3 },
  { uuid: 30, nombre: 'Levanto', provincia: 3 },
  { uuid: 31, nombre: 'Magdalena', provincia: 3 },
  { uuid: 32, nombre: 'Mariscal Castilla', provincia: 3 },
  { uuid: 33, nombre: 'Molinopampa', provincia: 3 },
  { uuid: 34, nombre: 'Montevideo', provincia: 3 },
  { uuid: 35, nombre: 'Olleros', provincia: 3 },
  { uuid: 36, nombre: 'Quinjalca', provincia: 3 },
  { uuid: 37, nombre: 'San Francisco de Daguas', provincia: 3 },
  { uuid: 38, nombre: 'San Isidro de Maino', provincia: 3 },
  { uuid: 39, nombre: 'Soloco', provincia: 3 },
  { uuid: 40, nombre: 'Sonche', provincia: 3 },
  //
  { uuid: 41, nombre: 'El Cenepa', provincia: 4 },
  { uuid: 42, nombre: 'Nieva', provincia: 4 },
  { uuid: 43, nombre: 'Rio Santiago', provincia: 4 },
  //
  { uuid: 44, nombre: 'Camporredondo', provincia: 5 },
  { uuid: 45, nombre: 'Cocabamba', provincia: 5 },
  { uuid: 46, nombre: 'Colcamar', provincia: 5 },
  { uuid: 47, nombre: 'Conila', provincia: 5 },
  { uuid: 48, nombre: 'Inguilpata', provincia: 5 },
  { uuid: 49, nombre: 'Lámud', provincia: 5 },
  { uuid: 50, nombre: 'Longuita', provincia: 5 },
  { uuid: 51, nombre: 'Lonya Chico', provincia: 5 },
  { uuid: 52, nombre: 'Luya', provincia: 5 },
  { uuid: 53, nombre: 'Luya Viejo', provincia: 5 },
  { uuid: 54, nombre: 'María', provincia: 5 },
  { uuid: 55, nombre: 'Ocalli', provincia: 5 },
  { uuid: 56, nombre: 'Ocumal', provincia: 5 },
  { uuid: 57, nombre: 'Pisuquía', provincia: 5 },
  { uuid: 58, nombre: 'Providencia', provincia: 5 },
  { uuid: 59, nombre: 'San Cristóbal', provincia: 5 },
  { uuid: 60, nombre: 'San Francisco del Yeso', provincia: 5 },
  { uuid: 61, nombre: 'San Jerónimo', provincia: 5 },
  { uuid: 62, nombre: 'San Juan de Lopecancha', provincia: 5 },
  { uuid: 63, nombre: 'Santa Catalina', provincia: 5 },
  { uuid: 64, nombre: 'Santo Tomás', provincia: 5 },
  { uuid: 65, nombre: 'Tingo', provincia: 5 },
  { uuid: 66, nombre: 'Trita', provincia: 5 },
  //
  { uuid: 67, nombre: 'Chirimoto', provincia: 6 },
  { uuid: 68, nombre: 'Cochamal', provincia: 6 },
  { uuid: 69, nombre: 'Huambo', provincia: 6 },
  { uuid: 70, nombre: 'Limabamba', provincia: 6 },
  { uuid: 71, nombre: 'Longar', provincia: 6 },
  { uuid: 72, nombre: 'Mariscal Benavides', provincia: 6 },
  { uuid: 73, nombre: 'Milpuc', provincia: 6 },
  { uuid: 74, nombre: 'Omia', provincia: 6 },
  { uuid: 75, nombre: 'San Nicolás', provincia: 6 },
  { uuid: 76, nombre: 'Santa Rosa', provincia: 6 },
  { uuid: 77, nombre: 'Totora', provincia: 6 },
  { uuid: 78, nombre: 'Vista Alegre', provincia: 6 },
  //
  { uuid: 79, nombre: 'Bagua Grande', provincia: 7 },
  { uuid: 80, nombre: 'Cajaruro', provincia: 7 },
  { uuid: 81, nombre: 'Cumba', provincia: 7 },
  { uuid: 82, nombre: 'El Milagro', provincia: 7 },
  { uuid: 83, nombre: 'Jamalca', provincia: 7 },
  { uuid: 84, nombre: 'Lonya Grande', provincia: 7 },
  { uuid: 85, nombre: 'Yamón', provincia: 7 },
  //
  { uuid: 86, nombre: 'Chanchamayo', provincia: 8 },
  { uuid: 87, nombre: 'Perené', provincia: 8 },
  { uuid: 88, nombre: 'Pichanaqui', provincia: 8 },
  { uuid: 89, nombre: 'San Luis de Shuaro', provincia: 8 },
  { uuid: 90, nombre: 'San Ramón', provincia: 8 },
  { uuid: 91, nombre: 'Vítoc', provincia: 8 },
  //
  { uuid: 92, nombre: 'Áhuac', provincia: 9 },
  { uuid: 93, nombre: 'Chongos Bajo', provincia: 9 },
  { uuid: 94, nombre: 'Chupaca', provincia: 9 },
  { uuid: 95, nombre: 'Huáchac', provincia: 9 },
  { uuid: 96, nombre: 'Huamancaca Chico', provincia: 9 },
  { uuid: 97, nombre: 'San Juan de Jarpa', provincia: 9 },
  { uuid: 98, nombre: 'San Juan de Yscos', provincia: 9 },
  { uuid: 99, nombre: 'Tres de Diciembre', provincia: 9 },
  { uuid: 100, nombre: 'Yanacancha', provincia: 9 },
  //
  { uuid: 101, nombre: 'Aco', provincia: 10 },
  { uuid: 102, nombre: 'Andamarca', provincia: 10 },
  { uuid: 103, nombre: 'Chambara', provincia: 10 },
  { uuid: 104, nombre: 'Cochas', provincia: 10 },
  { uuid: 105, nombre: 'Comas', provincia: 10 },
  { uuid: 106, nombre: 'Concepción', provincia: 10 },
  { uuid: 107, nombre: 'Heroínas Toledo', provincia: 10 },
  { uuid: 108, nombre: 'Manzanares', provincia: 10 },
  { uuid: 109, nombre: 'Mariscal Castilla', provincia: 10 },
  { uuid: 110, nombre: 'Matahuasi', provincia: 10 },
  { uuid: 111, nombre: 'Mito', provincia: 10 },
  { uuid: 112, nombre: 'Nueve de Julio', provincia: 10 },
  { uuid: 113, nombre: 'Orcotuna', provincia: 10 },
  { uuid: 114, nombre: 'San José de Quero', provincia: 10 },
  { uuid: 115, nombre: 'Santa Rosa de Ocopa', provincia: 10 },
  //
  { uuid: 116, nombre: 'Carhuacallanga', provincia: 11 },
  { uuid: 117, nombre: 'Chacapampa', provincia: 11 },
  { uuid: 118, nombre: 'Chicche', provincia: 11 },
  { uuid: 119, nombre: 'Chilca', provincia: 11 },
  { uuid: 120, nombre: 'Chongos Alto', provincia: 11 },
  { uuid: 121, nombre: 'Chupuro', provincia: 11 },
  { uuid: 122, nombre: 'Colca', provincia: 11 },
  { uuid: 123, nombre: 'Cullhuas', provincia: 11 },
  { uuid: 124, nombre: 'El Tambo', provincia: 11 },
  { uuid: 125, nombre: 'Huacrapuquio', provincia: 11 },
  { uuid: 126, nombre: 'Hualhuas', provincia: 11 },
  { uuid: 127, nombre: 'Huancán', provincia: 11 },
  { uuid: 128, nombre: 'Huancayo', provincia: 11 },
  { uuid: 129, nombre: 'Huasicancha', provincia: 11 },
  { uuid: 130, nombre: 'Huayucachi', provincia: 11 },
  { uuid: 131, nombre: 'Ingenio', provincia: 11 },
  { uuid: 132, nombre: 'Pariahuanca', provincia: 11 },
  { uuid: 133, nombre: 'Pilcomayo', provincia: 11 },
  { uuid: 134, nombre: 'Pucará', provincia: 11 },
  { uuid: 135, nombre: 'Quichuay', provincia: 11 },
  { uuid: 136, nombre: 'Quilcas', provincia: 11 },
  { uuid: 137, nombre: 'San Agustín de Cajas', provincia: 11 },
  { uuid: 138, nombre: 'San Jerónimo de Tunán', provincia: 11 },
  { uuid: 139, nombre: 'San Pedro de Saño', provincia: 11 },
  { uuid: 140, nombre: 'Santo Domingo de Acobamba', provincia: 11 },
  { uuid: 141, nombre: 'Sapallanga', provincia: 11 },
  { uuid: 142, nombre: 'Sicaya', provincia: 11 },
  { uuid: 143, nombre: 'Viques', provincia: 11 },
  //
  { uuid: 144, nombre: 'Acolla', provincia: 12 },
  { uuid: 145, nombre: 'Apata', provincia: 12 },
  { uuid: 146, nombre: 'Ataura', provincia: 12 },
  { uuid: 147, nombre: 'Canchayllo', provincia: 12 },
  { uuid: 148, nombre: 'Curicaca', provincia: 12 },
  { uuid: 149, nombre: 'El Mantaro', provincia: 12 },
  { uuid: 150, nombre: 'Huamalí', provincia: 12 },
  { uuid: 151, nombre: 'Huaripampa', provincia: 12 },
  { uuid: 152, nombre: 'Huertas', provincia: 12 },
  { uuid: 153, nombre: 'Janjaillo', provincia: 12 },
  { uuid: 154, nombre: 'Jauja', provincia: 12 },
  { uuid: 155, nombre: 'Julcán', provincia: 12 },
  { uuid: 156, nombre: 'Leonor Ordóñez', provincia: 12 },
  { uuid: 157, nombre: 'Llocllapampa', provincia: 12 },
  { uuid: 158, nombre: 'Marco', provincia: 12 },
  { uuid: 159, nombre: 'Masma', provincia: 12 },
  { uuid: 160, nombre: 'Masma Chicche', provincia: 12 },
  { uuid: 161, nombre: 'Molinos', provincia: 12 },
  { uuid: 162, nombre: 'Monobamba', provincia: 12 },
  { uuid: 163, nombre: 'Muqui', provincia: 12 },
  { uuid: 164, nombre: 'Muquiyauyo', provincia: 12 },
  { uuid: 165, nombre: 'Paca', provincia: 12 },
  { uuid: 166, nombre: 'Paccha', provincia: 12 },
  { uuid: 167, nombre: 'Pancán', provincia: 12 },
  { uuid: 168, nombre: 'Parco', provincia: 12 },
  { uuid: 169, nombre: 'Pomacancha', provincia: 12 },
  { uuid: 170, nombre: 'Ricrán', provincia: 12 },
  { uuid: 171, nombre: 'San Lorenzo', provincia: 12 },
  { uuid: 172, nombre: 'San Pedro de Chunán', provincia: 12 },
  { uuid: 173, nombre: 'Sausa', provincia: 12 },
  { uuid: 174, nombre: 'Sincos', provincia: 12 },
  { uuid: 175, nombre: 'Tunanmarca', provincia: 12 },
  { uuid: 176, nombre: 'Yauli', provincia: 12 },
  { uuid: 177, nombre: 'Yauyos', provincia: 12 },
  //
  { uuid: 178, nombre: 'Carhuamayo', provincia: 13 },
  { uuid: 179, nombre: 'Junín', provincia: 13 },
  { uuid: 180, nombre: 'Ondores', provincia: 13 },
  { uuid: 181, nombre: 'Ulcumayo', provincia: 13 },
  //
  { uuid: 182, nombre: 'Coviriali', provincia: 14 },
  { uuid: 183, nombre: 'Llaylla', provincia: 14 },
  { uuid: 184, nombre: 'Mazamari', provincia: 14 },
  { uuid: 185, nombre: 'Pampa Hermosa', provincia: 14 },
  { uuid: 186, nombre: 'Pangoa', provincia: 14 },
  { uuid: 187, nombre: 'Río Negro', provincia: 14 },
  { uuid: 188, nombre: 'Río Tambo', provincia: 14 },
  { uuid: 189, nombre: 'Satipo', provincia: 14 },
  { uuid: 190, nombre: 'Vizcatán del Ene', provincia: 14 },
  //
  { uuid: 191, nombre: 'Acobamba', provincia: 15 },
  { uuid: 192, nombre: 'Huaricolca', provincia: 15 },
  { uuid: 193, nombre: 'Huasahuasi', provincia: 15 },
  { uuid: 194, nombre: 'La Unión', provincia: 15 },
  { uuid: 195, nombre: 'Palca', provincia: 15 },
  { uuid: 196, nombre: 'Palcamayo', provincia: 15 },
  { uuid: 197, nombre: 'San Pedro de Cajas', provincia: 15 },
  { uuid: 198, nombre: 'Tapo', provincia: 15 },
  { uuid: 199, nombre: 'Tarma', provincia: 15 },
  //
  { uuid: 200, nombre: 'Chacapalpa', provincia: 16 },
  { uuid: 201, nombre: 'Huayhuay', provincia: 16 },
  { uuid: 202, nombre: 'La Oroya', provincia: 16 },
  { uuid: 203, nombre: 'Marcapomacocha', provincia: 16 },
  { uuid: 204, nombre: 'Morococha', provincia: 16 },
  { uuid: 205, nombre: 'Paccha', provincia: 16 },
  { uuid: 206, nombre: 'Santa Barbara de Carhuacayán', provincia: 16 },
  { uuid: 207, nombre: 'Santa Rosa de Sacco', provincia: 16 },
  { uuid: 208, nombre: 'Suitucancha', provincia: 16 },
  { uuid: 209, nombre: 'Yauli', provincia: 16 }
]

export const direcciones: IDireccion[] = [
  {
    nombre: 'Av. La Marina 456',
    referencia: 'Frente al hospital central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Calle Las Flores 789',
    referencia: 'Al costado del parque central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Jr. Los Pinos 1011',
    referencia: 'Cerca al centro histórico',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Av. Brasil 1213',
    referencia: 'Frente al centro deportivo',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Jr. Las Azucenas 1415',
    referencia: 'Cerca al mercado central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Calle Los Pájaros 1617',
    referencia: 'Cerca al aeropuerto',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Av. Los Olivos 1819',
    referencia: 'Cerca a la estación de tren',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Jr. Las Rosas 2021',
    referencia: 'Cerca al centro comercial',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Av. El Sol 2223',
    referencia: 'Cerca al parque principal',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
  {
    nombre: 'Calle Las Palmeras 2425',
    referencia: 'Cerca a la plaza de la iglesia',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
  },
];