import { IDireccion } from "types-prestamista"

export const departamentos = [
  { id: 1, nombre: 'Amazonas' },
  { id: 2, nombre: 'Ancash' },
  { id: 3, nombre: 'Apurímac' },
  { id: 4, nombre: 'Arequipa' },
  { id: 5, nombre: 'Ayacucho' },
  { id: 6, nombre: 'Cajamarca' },
  { id: 7, nombre: 'Callao' },
  { id: 8, nombre: 'Cusco' },
  { id: 9, nombre: 'Huancavelica' },
  { id: 10, nombre: 'Huánuco' },
  { id: 11, nombre: 'Ica' },
  { id: 12, nombre: 'Junín' },
  { id: 13, nombre: 'La Libertad' },
  { id: 14, nombre: 'Lambayeque' },
  { id: 15, nombre: 'lima' },
  { id: 16, nombre: 'Loreto' },
  { id: 17, nombre: 'Madre de Dios' },
  { id: 18, nombre: 'Moquegua' },
  { id: 19, nombre: 'Pasco' },
  { id: 20, nombre: 'Piura' },
  { id: 21, nombre: 'Puno' },
  { id: 22, nombre: 'San Martín' },
  { id: 23, nombre: 'Tacna' },
  { id: 24, nombre: 'Tumbes' },
  { id: 25, nombre: 'Ucayali' }
]

export const provincias = [
  { id: 1, nombre: 'Bagua', departamento: 1 },
  { id: 2, nombre: 'Bongará', departamento: 1 },
  { id: 3, nombre: 'Chachapoyas', departamento: 1 },
  { id: 4, nombre: 'Condorcanqui', departamento: 1 },
  { id: 5, nombre: 'Luya', departamento: 1 },
  { id: 6, nombre: 'Rodríguez de Mendoza', departamento: 1 },
  { id: 7, nombre: 'Utcubamba', departamento: 1 },
  //
  { id: 8, nombre: 'Chanchamayo', departamento: 12 },
  { id: 9, nombre: 'Chupaca', departamento: 12 },
  { id: 10, nombre: 'Concepción', departamento: 12 },
  { id: 11, nombre: 'Huancayo', departamento: 12 },
  { id: 12, nombre: 'Jauja', departamento: 12 },
  { id: 13, nombre: 'Junín', departamento: 12 },
  { id: 14, nombre: 'Satipo', departamento: 12 },
  { id: 15, nombre: 'Tarma', departamento: 12 },
  { id: 16, nombre: 'Yauli', departamento: 12 }
]

export const distritos = [
  { id: 1, nombre: 'Aramango', provincia: 1 },
  { id: 2, nombre: 'Bagua', provincia: 1 },
  { id: 3, nombre: 'Copallín', provincia: 1 },
  { id: 4, nombre: 'El parco', provincia: 1 },
  { id: 5, nombre: 'Imaza', provincia: 1 },
  { id: 6, nombre: 'La peca', provincia: 1 },
  { id: 7, nombre: 'Shipasbamba', provincia: 1 },
  //
  { id: 8, nombre: 'Chisquilla', provincia: 2 },
  { id: 9, nombre: 'Churuja', provincia: 2 },
  { id: 10, nombre: 'Corocha', provincia: 2 },
  { id: 11, nombre: 'Cuispes', provincia: 2 },
  { id: 12, nombre: 'Florida', provincia: 2 },
  { id: 13, nombre: 'Jumbila', provincia: 2 },
  { id: 14, nombre: 'Pedro Ruiz Gallo', provincia: 2 },
  { id: 15, nombre: 'Recta', provincia: 2 },
  { id: 16, nombre: 'San Carlos', provincia: 2 },
  { id: 17, nombre: 'Shipasbamba', provincia: 2 },
  { id: 18, nombre: 'Valera', provincia: 2 },
  { id: 19, nombre: 'Yambrasbamba', provincia: 2 },
  //
  { id: 20, nombre: 'Asunción', provincia: 3 },
  { id: 21, nombre: 'Balsa', provincia: 3 },
  { id: 22, nombre: 'Chachapoyas', provincia: 3 },
  { id: 23, nombre: 'Cheto', provincia: 3 },
  { id: 24, nombre: 'Chiliquín', provincia: 3 },
  { id: 25, nombre: 'Chuquibamba', provincia: 3 },
  { id: 26, nombre: 'Granada', provincia: 3 },
  { id: 27, nombre: 'Huancas', provincia: 3 },
  { id: 28, nombre: 'La Jalca', provincia: 3 },
  { id: 29, nombre: 'Leimebamba', provincia: 3 },
  { id: 30, nombre: 'Levanto', provincia: 3 },
  { id: 31, nombre: 'Magdalena', provincia: 3 },
  { id: 32, nombre: 'Mariscal Castilla', provincia: 3 },
  { id: 33, nombre: 'Molinopampa', provincia: 3 },
  { id: 34, nombre: 'Montevideo', provincia: 3 },
  { id: 35, nombre: 'Olleros', provincia: 3 },
  { id: 36, nombre: 'Quinjalca', provincia: 3 },
  { id: 37, nombre: 'San Francisco de Daguas', provincia: 3 },
  { id: 38, nombre: 'San Isidro de Maino', provincia: 3 },
  { id: 39, nombre: 'Soloco', provincia: 3 },
  { id: 40, nombre: 'Sonche', provincia: 3 },
  //
  { id: 41, nombre: 'El Cenepa', provincia: 4 },
  { id: 42, nombre: 'Nieva', provincia: 4 },
  { id: 43, nombre: 'Rio Santiago', provincia: 4 },
  //
  { id: 44, nombre: 'Camporredondo', provincia: 5 },
  { id: 45, nombre: 'Cocabamba', provincia: 5 },
  { id: 46, nombre: 'Colcamar', provincia: 5 },
  { id: 47, nombre: 'Conila', provincia: 5 },
  { id: 48, nombre: 'Inguilpata', provincia: 5 },
  { id: 49, nombre: 'Lámud', provincia: 5 },
  { id: 50, nombre: 'Longuita', provincia: 5 },
  { id: 51, nombre: 'Lonya Chico', provincia: 5 },
  { id: 52, nombre: 'Luya', provincia: 5 },
  { id: 53, nombre: 'Luya Viejo', provincia: 5 },
  { id: 54, nombre: 'María', provincia: 5 },
  { id: 55, nombre: 'Ocalli', provincia: 5 },
  { id: 56, nombre: 'Ocumal', provincia: 5 },
  { id: 57, nombre: 'Pisuquía', provincia: 5 },
  { id: 58, nombre: 'Providencia', provincia: 5 },
  { id: 59, nombre: 'San Cristóbal', provincia: 5 },
  { id: 60, nombre: 'San Francisco del Yeso', provincia: 5 },
  { id: 61, nombre: 'San Jerónimo', provincia: 5 },
  { id: 62, nombre: 'San Juan de Lopecancha', provincia: 5 },
  { id: 63, nombre: 'Santa Catalina', provincia: 5 },
  { id: 64, nombre: 'Santo Tomás', provincia: 5 },
  { id: 65, nombre: 'Tingo', provincia: 5 },
  { id: 66, nombre: 'Trita', provincia: 5 },
  //
  { id: 67, nombre: 'Chirimoto', provincia: 6 },
  { id: 68, nombre: 'Cochamal', provincia: 6 },
  { id: 69, nombre: 'Huambo', provincia: 6 },
  { id: 70, nombre: 'Limabamba', provincia: 6 },
  { id: 71, nombre: 'Longar', provincia: 6 },
  { id: 72, nombre: 'Mariscal Benavides', provincia: 6 },
  { id: 73, nombre: 'Milpuc', provincia: 6 },
  { id: 74, nombre: 'Omia', provincia: 6 },
  { id: 75, nombre: 'San Nicolás', provincia: 6 },
  { id: 76, nombre: 'Santa Rosa', provincia: 6 },
  { id: 77, nombre: 'Totora', provincia: 6 },
  { id: 78, nombre: 'Vista Alegre', provincia: 6 },
  //
  { id: 79, nombre: 'Bagua Grande', provincia: 7 },
  { id: 80, nombre: 'Cajaruro', provincia: 7 },
  { id: 81, nombre: 'Cumba', provincia: 7 },
  { id: 82, nombre: 'El Milagro', provincia: 7 },
  { id: 83, nombre: 'Jamalca', provincia: 7 },
  { id: 84, nombre: 'Lonya Grande', provincia: 7 },
  { id: 85, nombre: 'Yamón', provincia: 7 },
  //
  { id: 86, nombre: 'Chanchamayo', provincia: 8 },
  { id: 87, nombre: 'Perené', provincia: 8 },
  { id: 88, nombre: 'Pichanaqui', provincia: 8 },
  { id: 89, nombre: 'San Luis de Shuaro', provincia: 8 },
  { id: 90, nombre: 'San Ramón', provincia: 8 },
  { id: 91, nombre: 'Vítoc', provincia: 8 },
  //
  { id: 92, nombre: 'Áhuac', provincia: 9 },
  { id: 93, nombre: 'Chongos Bajo', provincia: 9 },
  { id: 94, nombre: 'Chupaca', provincia: 9 },
  { id: 95, nombre: 'Huáchac', provincia: 9 },
  { id: 96, nombre: 'Huamancaca Chico', provincia: 9 },
  { id: 97, nombre: 'San Juan de Jarpa', provincia: 9 },
  { id: 98, nombre: 'San Juan de Yscos', provincia: 9 },
  { id: 99, nombre: 'Tres de Diciembre', provincia: 9 },
  { id: 100, nombre: 'Yanacancha', provincia: 9 },
  //
  { id: 101, nombre: 'Aco', provincia: 10 },
  { id: 102, nombre: 'Andamarca', provincia: 10 },
  { id: 103, nombre: 'Chambara', provincia: 10 },
  { id: 104, nombre: 'Cochas', provincia: 10 },
  { id: 105, nombre: 'Comas', provincia: 10 },
  { id: 106, nombre: 'Concepción', provincia: 10 },
  { id: 107, nombre: 'Heroínas Toledo', provincia: 10 },
  { id: 108, nombre: 'Manzanares', provincia: 10 },
  { id: 109, nombre: 'Mariscal Castilla', provincia: 10 },
  { id: 110, nombre: 'Matahuasi', provincia: 10 },
  { id: 111, nombre: 'Mito', provincia: 10 },
  { id: 112, nombre: 'Nueve de Julio', provincia: 10 },
  { id: 113, nombre: 'Orcotuna', provincia: 10 },
  { id: 114, nombre: 'San José de Quero', provincia: 10 },
  { id: 115, nombre: 'Santa Rosa de Ocopa', provincia: 10 },
  //
  { id: 116, nombre: 'Carhuacallanga', provincia: 11 },
  { id: 117, nombre: 'Chacapampa', provincia: 11 },
  { id: 118, nombre: 'Chicche', provincia: 11 },
  { id: 119, nombre: 'Chilca', provincia: 11 },
  { id: 120, nombre: 'Chongos Alto', provincia: 11 },
  { id: 121, nombre: 'Chupuro', provincia: 11 },
  { id: 122, nombre: 'Colca', provincia: 11 },
  { id: 123, nombre: 'Cullhuas', provincia: 11 },
  { id: 124, nombre: 'El Tambo', provincia: 11 },
  { id: 125, nombre: 'Huacrapuquio', provincia: 11 },
  { id: 126, nombre: 'Hualhuas', provincia: 11 },
  { id: 127, nombre: 'Huancán', provincia: 11 },
  { id: 128, nombre: 'Huancayo', provincia: 11 },
  { id: 129, nombre: 'Huasicancha', provincia: 11 },
  { id: 130, nombre: 'Huayucachi', provincia: 11 },
  { id: 131, nombre: 'Ingenio', provincia: 11 },
  { id: 132, nombre: 'Pariahuanca', provincia: 11 },
  { id: 133, nombre: 'Pilcomayo', provincia: 11 },
  { id: 134, nombre: 'Pucará', provincia: 11 },
  { id: 135, nombre: 'Quichuay', provincia: 11 },
  { id: 136, nombre: 'Quilcas', provincia: 11 },
  { id: 137, nombre: 'San Agustín de Cajas', provincia: 11 },
  { id: 138, nombre: 'San Jerónimo de Tunán', provincia: 11 },
  { id: 139, nombre: 'San Pedro de Saño', provincia: 11 },
  { id: 140, nombre: 'Santo Domingo de Acobamba', provincia: 11 },
  { id: 141, nombre: 'Sapallanga', provincia: 11 },
  { id: 142, nombre: 'Sicaya', provincia: 11 },
  { id: 143, nombre: 'Viques', provincia: 11 },
  //
  { id: 144, nombre: 'Acolla', provincia: 12 },
  { id: 145, nombre: 'Apata', provincia: 12 },
  { id: 146, nombre: 'Ataura', provincia: 12 },
  { id: 147, nombre: 'Canchayllo', provincia: 12 },
  { id: 148, nombre: 'Curicaca', provincia: 12 },
  { id: 149, nombre: 'El Mantaro', provincia: 12 },
  { id: 150, nombre: 'Huamalí', provincia: 12 },
  { id: 151, nombre: 'Huaripampa', provincia: 12 },
  { id: 152, nombre: 'Huertas', provincia: 12 },
  { id: 153, nombre: 'Janjaillo', provincia: 12 },
  { id: 154, nombre: 'Jauja', provincia: 12 },
  { id: 155, nombre: 'Julcán', provincia: 12 },
  { id: 156, nombre: 'Leonor Ordóñez', provincia: 12 },
  { id: 157, nombre: 'Llocllapampa', provincia: 12 },
  { id: 158, nombre: 'Marco', provincia: 12 },
  { id: 159, nombre: 'Masma', provincia: 12 },
  { id: 160, nombre: 'Masma Chicche', provincia: 12 },
  { id: 161, nombre: 'Molinos', provincia: 12 },
  { id: 162, nombre: 'Monobamba', provincia: 12 },
  { id: 163, nombre: 'Muqui', provincia: 12 },
  { id: 164, nombre: 'Muquiyauyo', provincia: 12 },
  { id: 165, nombre: 'Paca', provincia: 12 },
  { id: 166, nombre: 'Paccha', provincia: 12 },
  { id: 167, nombre: 'Pancán', provincia: 12 },
  { id: 168, nombre: 'Parco', provincia: 12 },
  { id: 169, nombre: 'Pomacancha', provincia: 12 },
  { id: 170, nombre: 'Ricrán', provincia: 12 },
  { id: 171, nombre: 'San Lorenzo', provincia: 12 },
  { id: 172, nombre: 'San Pedro de Chunán', provincia: 12 },
  { id: 173, nombre: 'Sausa', provincia: 12 },
  { id: 174, nombre: 'Sincos', provincia: 12 },
  { id: 175, nombre: 'Tunanmarca', provincia: 12 },
  { id: 176, nombre: 'Yauli', provincia: 12 },
  { id: 177, nombre: 'Yauyos', provincia: 12 },
  //
  { id: 178, nombre: 'Carhuamayo', provincia: 13 },
  { id: 179, nombre: 'Junín', provincia: 13 },
  { id: 180, nombre: 'Ondores', provincia: 13 },
  { id: 181, nombre: 'Ulcumayo', provincia: 13 },
  //
  { id: 182, nombre: 'Coviriali', provincia: 14 },
  { id: 183, nombre: 'Llaylla', provincia: 14 },
  { id: 184, nombre: 'Mazamari', provincia: 14 },
  { id: 185, nombre: 'Pampa Hermosa', provincia: 14 },
  { id: 186, nombre: 'Pangoa', provincia: 14 },
  { id: 187, nombre: 'Río Negro', provincia: 14 },
  { id: 188, nombre: 'Río Tambo', provincia: 14 },
  { id: 189, nombre: 'Satipo', provincia: 14 },
  { id: 190, nombre: 'Vizcatán del Ene', provincia: 14 },
  //
  { id: 191, nombre: 'Acobamba', provincia: 15 },
  { id: 192, nombre: 'Huaricolca', provincia: 15 },
  { id: 193, nombre: 'Huasahuasi', provincia: 15 },
  { id: 194, nombre: 'La Unión', provincia: 15 },
  { id: 195, nombre: 'Palca', provincia: 15 },
  { id: 196, nombre: 'Palcamayo', provincia: 15 },
  { id: 197, nombre: 'San Pedro de Cajas', provincia: 15 },
  { id: 198, nombre: 'Tapo', provincia: 15 },
  { id: 199, nombre: 'Tarma', provincia: 15 },
  //
  { id: 200, nombre: 'Chacapalpa', provincia: 16 },
  { id: 201, nombre: 'Huayhuay', provincia: 16 },
  { id: 202, nombre: 'La Oroya', provincia: 16 },
  { id: 203, nombre: 'Marcapomacocha', provincia: 16 },
  { id: 204, nombre: 'Morococha', provincia: 16 },
  { id: 205, nombre: 'Paccha', provincia: 16 },
  { id: 206, nombre: 'Santa Barbara de Carhuacayán', provincia: 16 },
  { id: 207, nombre: 'Santa Rosa de Sacco', provincia: 16 },
  { id: 208, nombre: 'Suitucancha', provincia: 16 },
  { id: 209, nombre: 'Yauli', provincia: 16 }
]

export const direcciones: IDireccion[] = [
  {
    nombre: 'Av. La Marina 456',
    referencia: 'Frente al hospital central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Calle Las Flores 789',
    referencia: 'Al costado del parque central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Jr. Los Pinos 1011',
    referencia: 'Cerca al centro histórico',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Av. Brasil 1213',
    referencia: 'Frente al centro deportivo',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Jr. Las Azucenas 1415',
    referencia: 'Cerca al mercado central',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Calle Los Pájaros 1617',
    referencia: 'Cerca al aeropuerto',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Av. Los Olivos 1819',
    referencia: 'Cerca a la estación de tren',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Jr. Las Rosas 2021',
    referencia: 'Cerca al centro comercial',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Av. El Sol 2223',
    referencia: 'Cerca al parque principal',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
  {
    nombre: 'Calle Las Palmeras 2425',
    referencia: 'Cerca a la plaza de la iglesia',
    departamento: '' as any,
    provincia: '' as any,
    distrito: '' as any,
    cliente: '' as any,
  },
];