import { IProducto } from "types-yola";

export const productosTienda: Array<IProducto> = [
  {
    nombre: "Mandarina",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "CAJAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 75, 
    precioVenta: 85, 
    alertaCantidad: 15, 
    sobrante: 5,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La mandarina es una fruta tropical de la familia de las Rutáceas, con un color amarillo pálido, una sutil textura y una gran pureza. Su sabor es dulce y su aroma es fresco. La mandarina es una fruta de gran calidad, que se cultiva en todo el mundo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534997/productos/recorte%20200/mandarina-min-min_o2pqys.png",
    marca: "",
    tags: ['anaranjado', 'fruta', 'citrico'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Limón",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El limón es una fruta tropical de la familia de las Rutáceas, con un color amarillo pálido, una sutil textura y una gran pureza. Su sabor es dulce y su aroma es fresco. El limón es una fruta de gran calidad, que se cultiva en todo el mundo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534997/productos/recorte%20200/mandarina-min-min_o2pqys.png",
    marca: "",
    tags: ['verde', 'fruta', 'citrico'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Mango",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El mango, es el nombre de las frutas de varias especies de árboles del género Mangifera, especialmente de Mangifera indica, y sus numerosos cultivares.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534997/productos/recorte%20200/mango-min-min_dlvvbz.png",
    marca: "",
    tags: ['amarillo', 'fruta', 'mangifera'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 6 },
      { peso: 500, precio: 3},
      { peso: 250, precio: 1.5}
    ],
    precioUnidad: 5.0
  },
 
  {
    nombre: "Granadilla",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La granadilla es una fruta tropical de la familia de las Rutáceas, con un color amarillo pálido, una sutil textura y una gran pureza. Su sabor es dulce y su aroma es fresco. La granadilla es una fruta de gran calidad, que se cultiva en todo el mundo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/granadilla-min-min_eryloy.png",
    marca: "",
    tags: ['amarillo', 'dulce', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Kion",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El jengibre o kion ​ es una planta de la familia de las zingiberáceas, cuyo tallo subterráneo es un rizoma horizontal muy apreciado por su aroma y sabor picante. La planta llega a tener 90 cm de altura, con largas hojas de 20 cm.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/kion-min-min_s3kqzn.png",
    marca: "",
    tags: ['amarillo', 'picante', 'planta', 'jengibre'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Col repollo",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Planta hortícola de hojas verdes muy anchas y arrugadas, de pencas gruesas, flores pequeñas, de color blanco o amarillo, agrupadas en panoja, en el extremo de un tallo y semilla muy pequeña; las hojas están tan unidas y apretadas entre sí que forman una especie de pelota",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/col_repollo-min-min_nilvvy.png",
    marca: "",
    tags: ['verde', 'planta', 'ensalada', 'col'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 3 },
      { peso: 500, precio: 2},
      { peso: 250, precio: 1.5}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Coliflor",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La coliflor es una hortaliza perteneciente a la familia de las coles. La parte que se consume es la flor o inflorescencia, muy apreciada por su sabor",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/coliflor-min-min_emkhrf.png",
    marca: "",
    tags: ['blanco', 'planta', 'ensalada', 'col'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 3 },
      { peso: 500, precio: 2},
      { peso: 250, precio: 1.5}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Culantro",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El culantro coyote es una hoja rica en: Hierro, previene la anemia. Ácido fólico, protege de transtornos gastrointestinales. Fibra, mejora el tránsito gastrointestinal, regula los niveles de azúcar y colesterol, y se relaciona con la saciedad",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/culantro-min-min_ztexhu.png",
    marca: "",
    tags: ['verde', 'planta', 'ensalada', 'culantro'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Col crespo",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El Col crespo es un repollo de hojas más ó menos rizadas, compactas y cerosas. Se adapta a gran variedad de terrenos, pero es exigente en agua y le conviene enmiendas orgánicas. Se usa la plantación en terreno con una densidad de alrededor de 35,000 plantas por Ha.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/col_crespo-min-min_kpzsfw.png",
    marca: "",
    tags: ['col', 'crespo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 2.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.0}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Cebolla blanca",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 50, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "A menudo se reconoce a la cebolla como la reina de las verduras por su versatilidad culinaria, intenso sabor, sus cualidades terapéuticas, las poderosas propiedades antisépticas. La cebolla puede comerse cruda en ensalada y como condimento.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/cebolla_blanca-min-min_f7vthl.png",
    marca: "",
    tags: ['blanca', 'ensalada', 'adreso'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 2.0 },
      { peso: 500, precio: 1.0},
      { peso: 250, precio: 0.5}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Col corazon",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 50, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La col corazon es una planta de la familia de las coles, que se cultiva en el sur de América. Es una planta de hojas verdes, de color verde oscuro, con una base de pelos cortos, que se pueden cortar en varias partes. Se puede comerse cruda o en ensalada.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/col_china-min-min_hjz4fa.png",
    marca: "",
    tags: ['verde', 'planta', 'ensalada', 'col'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Camote morado",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 50, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El camote morado o Ipomoea batatas, es una especie originaria de México, que abunda en la región central, en especial en zonas como la sierra norte de Puebla, la sierra Zongolica de Veracruz; así como en los estados de Jalisco, Guanajuato y de México. Aunque se cree que llegó a nuestro continente desde China.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/camote_morado-min-min_qsssjw.png",
    marca: "",
    tags: ['morado', 'tuberculo', 'ensalada', 'camote'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 1.5 },
      { peso: 500, precio: 0.8},
      { peso: 250, precio: 0.4}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Cebolla roja",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La cebolla roja es una planta de la familia de las cebollas, que se cultiva en el sur de América. Es una planta de hojas verdes, de color rojo, con una base de pelos cortos, que se pueden cortar en varias partes. Se puede comerse cruda o en ensalada.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/cebolla_roja-min-min_qzshih.png",
    marca: "",
    tags: ['roja', 'ensalada', 'adreso'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Cebolla china",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La cebolla china es una planta de la familia de las cebollas, que se cultiva en el sur de América. Es una planta de hojas verdes, de color verde, con una base de pelos cortos, que se pueden cortar en varias partes. Se puede comerse cruda o en ensalada.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/cebolla_china-min-min_dun2i6.png",
    marca: "",
    tags: ['roja', 'ensalada', 'adreso'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Camote amarillo",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El Camote es un tubérculo nativo de los trópicos de América Latina, Centro y sur de México, Centro América y Selva Peruana. Es un bejuco perenne. aunque cultivado como anual. Crece a nivel o un poco arriba de la superficie del suelo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534996/productos/recorte%20200/camote_amarillo-min-min_y9vpbv.png",
    marca: "",
    tags: ['amarillo', 'tuberculo', 'camote'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5},
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Apio",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El Apio es una planta de la familia de las apícolas, que se cultiva en el sur de América. Es una planta de hojas verdes, de color verde, con una base de pelos cortos, que se pueden cortar en varias partes. Se puede comerse cruda o en ensalada.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/apio-min-min_gvsara.png",
    marca: "",
    tags: ['verde', 'ensalada'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 2 },
      { peso: 500, precio: 1.0},
      { peso: 250, precio: 0.5}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Brocoli",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Este es un tipo de plantas perteneciente a la familia de las Brasicaceas, familia de la cual es miembro el coliflor",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/apio-min-min_gvsara.png",
    marca: "",
    tags: ['verde', 'ensalada'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 3.5 },
      { peso: 500, precio: 1.8},
      { peso: 250, precio: 0.9}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Aji amarillo",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Se trata de un pimiento con un picante muy moderado y soportable, sobre todo si no se consumen sus semillas. Su sabor es muy característico y apreciado hasta el punto de que muchos peruanos afirman que es el ingrediente más importante te su cocina.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/aji_amarillo-min-min_yfqpol.png",
    marca: "",
    tags: ['amarillo', 'aji', 'picante'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 6.0 },
      { peso: 500, precio: 3.5 },
      { peso: 250, precio: 1.8 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Beterraga",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La remolacha es la raíz grande y carnosa que crece en la planta del mismo nombre y que se consume como hortaliza.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/beterraga-min-min_un8b11.png",
    marca: "",
    tags: ['rojo', 'ensalada', 'remolacha'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 2.0 },
      { peso: 500, precio: 1.0 },
      { peso: 250, precio: 0.5 }
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Alverjitas",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Pisum sativum es una planta herbácea de la familia de las leguminosas, más o menos trepadora, propia de la cuenca mediterránea, aunque muy extendida en todo el mundo'",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/beterraga-min-min_un8b11.png",
    marca: "",
    tags: ['verde', 'arroz con pollo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Aceite ideal",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "Pisum sativum es una planta herbácea de la familia de las leguminosas, más o menos trepadora, propia de la cuenca mediterránea, aunque muy extendida en todo el mundo'",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/aceite_c8sfwv.png",
    marca: "ideal",
    tags: ['aceite', 'frituras'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Atún florida",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "Pez marino de 2 a 3 m de longitud, color azul oscuro en el dorso y plateado en el vientre, que tiene de 8 a 10 pínulas o diminutas aletas junto a la cola, tanto en la parte dorsal como en la ventral, y la aleta caudal en forma de luna delgada; es activo y voraz; su carne es comestible.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/at%C3%BAn_mpeqwa.png",
    marca: "florida",
    tags: ['pescado', 'atun'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Azucar rubia",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "Es el producto sólido derivado de la caña de azúcar, constituido esencialmente por cristales sueltos de sacarosa, que se encuentran cubiertos por una película de su miel madre, en una concentración mínima de 96 % de polarización.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/azucar_aprxnb.png",
    marca: "",
    tags: ['azucar', 'rubia'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Café clasico",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "El café es la bebida que se obtiene a partir de los granos tostados y molidos de los frutos de la planta del café (cafeto); es altamente estimulante por su contenido de cafeína,​ una sustancia psicoactiva.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/cafe_omwah8.png",
    marca: "",
    tags: ['cafe'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Cocacola Zero",
    tipoVenta: "LITROS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La gaseosa, o bebida carbonatada, es una bebida saborizada, efervescente (carbonatada) y sin alcohol. Estas bebidas suelen consu- mirse frías, para ser más refrescantes y para evitar la pérdida de dióxido de carbono, que le otorga la efervescencia.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373215/productos/recorte%20200/cocacola_zero_bnlf5u.png",
    marca: "",
    tags: ['gaseosa', 'agua', 'refresco'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Coca-cola",
    tipoVenta: "LITROS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La gaseosa, o bebida carbonatada, es una bebida saborizada, efervescente (carbonatada) y sin alcohol. Estas bebidas suelen consu- mirse frías, para ser más refrescantes y para evitar la pérdida de dióxido de carbono, que le otorga la efervescencia.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/cocacola_xkxqnu.png",
    marca: "",
    tags: ['gaseosa', 'agua', 'refresco'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Durazno enlatado",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "Producto natural, no diluido, ni concentrado, ni fermentado, sin conservantes, obtenido por la desintegración y tamizado de la fracción comestible del durazno, sano y limpio. Sin preservantes, naturalmente libre de grasa y colesterol, bajo en sodio, contiene 100% de pulpa de fruta.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/durazno_igkkox.png",
    marca: "",
    tags: ['fruta', 'enlatado', 'durazno'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Codo rayado'",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La pasta es un conjunto de alimentos preparados con una masa cuyo ingrediente básico es la sémola, mezclada con agua, y a la cual se puede añadir sal, huevo u otros ingredientes, conformando un producto que generalmente se cuece en agua hirviendo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/fideos_2_e2ujof.png",
    marca: "",
    tags: ['fideos', 'canuto'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Fideos chinos",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La pasta es un conjunto de alimentos preparados con una masa cuyo ingrediente básico es la sémola, mezclada con agua, y a la cual se puede añadir sal, huevo u otros ingredientes, conformando un producto que generalmente se cuece en agua hirviendo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373218/productos/recorte%20200/fideos_chino_gij1rz.png",
    marca: "",
    tags: ['fideos', 'canuto'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Tallarines",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La pasta es un conjunto de alimentos preparados con una masa cuyo ingrediente básico es la sémola, mezclada con agua, y a la cual se puede añadir sal, huevo u otros ingredientes, conformando un producto que generalmente se cuece en agua hirviendo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/fideos_victorio_d01xtv.png",
    marca: "",
    tags: ['fideos', 'canuto'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Fresa",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "Entre sus minerales, las fresas aportan fundamentalmente potasio y magnesio, aunque también hierro, fósforo, yodo y calcio. Tienen 2,2 gramos de fibra por 100 gramos de producto, lo que supone un aporte moderado. Poseen grandes cantidades de elementos muy necesarios para nuestra salud.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/freza_wbe6cx.png",
    marca: "",
    tags: ['rojo', 'yogurt', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Granada",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La fruta posee una piel gruesa de color escarlata o dorada con tono carmesí en el exterior y una gran cantidad de semillas internas rodeadas de una jugosa pulpa de color rubí. Es una fruta de muy bajo valor calórico, debido a su escaso contenido de hidratos de carbono.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1651534995/productos/recorte%20200/alverja-min-min_omsxqd.png",
    marca: "",
    tags: ['rojo', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Guarana",
    tipoVenta: "LITROS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La gaseosa, o bebida carbonatada, es una bebida saborizada, efervescente (carbonatada) y sin alcohol. Estas bebidas suelen consu- mirse frías, para ser más refrescantes y para evitar la pérdida de dióxido de carbono, que le otorga la efervescencia.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/granada_cpez2w.png",
    marca: "",
    tags: ['anaranajado', 'gaseosa', 'agua'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Habas verde",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Haba - Información general. El haba es una hortaliza comestible, sus semillas y sus vainas pueden cocinarse de muy distintas formas, desde hervidas o como puré hasta como sopa de verano.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/habas_fcrrpn.png",
    marca: "",
    tags: ['verde', 'sopa'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Inka cola",
    tipoVenta: "LITROS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La gaseosa, o bebida carbonatada, es una bebida saborizada, efervescente (carbonatada) y sin alcohol. Estas bebidas suelen consu- mirse frías, para ser más refrescantes y para evitar la pérdida de dióxido de carbono, que le otorga la efervescencia.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/granada_cpez2w.png",
    marca: "",
    tags: ['amarillo' ],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Manzana de agua",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La manzana es el fruto comestible de la especie Malus domestica, el manzano común. Es una fruta pomácea de forma redonda y sabor muy dulce",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/manzana_de_agua_qfupo2.png",
    marca: "",
    tags: ['rojo', 'verde', 'manzana'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Manzana delicia",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La manzana es el fruto comestible de la especie Malus domestica, el manzano común. Es una fruta pomácea de forma redonda y sabor muy dulce",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/manzana_de_agua_qfupo2.png",
    marca: "",
    tags: ['rojo', 'verde', 'manzana'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Melon",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "Color: externamente amarillo, característico de la variedad, y pulpa de color homogéneo verde pálido. Apariencia: frutos esféricos (10-20 cm de diámetro.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/melon_trzz0a.png",
    marca: "",
    tags: ['fruta', 'amarillo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Olluco amarillo",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El olluco es un tubérculo que se cultiva en Perú desde tiempos ancestrales y en altitudes entre 1.000 y 4.000 metros. Hay una gran variedad de tipos desde color amarillo hasta rosaceo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373218/productos/recorte%20200/olluco_xic76f.png",
    marca: "",
    tags: ['amarillo', 'rojo', 'olluco'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Pepinos",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Es un alimento muy refrescante, por lo que resulta un optimo ingrediente en la preparación de ensaladas para hidratar al organismo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/pepino_qr2atj.png",
    marca: "",
    tags: ['verde', 'ensaladas'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Pera",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La pera es un alimento bajo en calorías y con poca acidez. Aporta vitamina C, fibra, potasio y vitamina E. Además tiene pequeñas cantidades de vitaminas B1 y B2, tiamina, rivoflavina, niacina y ácido ascórbico.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/melon_trzz0a.png",
    marca: "",
    tags: ['verde', 'frutas'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Piña",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "Frutas de forma cónica y ovaladas, de tamaño mediano, con hojas largas estrechas y espinosas, existe una variante con pocas espinas, con un borde central rojizo. Pulpa de color amarilla pálido, poco sensible a las enfermedades.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/pi%C3%B1a_gdopjg.png",
    marca: "",
    tags: ['amarillo', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Pitajaya",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La pitahaya es un un fruto que contiene antioxidantes, mucílagos, ácido ascórbico, fenoles. Es rica en Vitamina C, también contiene vitaminas del grupo B, minerales como calcio, fósforo, hierro",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/pitajaya_hpejpr.png",
    marca: "",
    tags: ['fruta', 'amarillo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 11.0 },
      { peso: 500, precio:  5.5 },
      { peso: 250, precio: 2.3  }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Platanos manzano",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "El plátano es una fruta tropical procedente de la planta herbácea que recibe el mismo nombre o banano, perteneciente a la familia de las musáceas. Tiene forma alargada o ligeramente curvada, de 100-200 g de peso. La piel es gruesa, de color amarillo y fácil de pelar, y la pulpa es blanca o amarillenta y carnosa.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/platanos_dgoo6b.png",
    marca: "",
    tags: ['amarillo', 'platano'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0  },
      { peso: 500, precio:  2.5 },
      { peso: 250, precio: 1.3  }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Pomarola",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La noción de pomarola se emplea en el terreno de la gastronomía para aludir a una salsa elaborada a base de tomate. El término puede vincularse al vocablo italiano pomodoro, que se traduce justamente como “tomate”.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/pomarola_aipazt.png",
    marca: "",
    tags: ['rojo', 'tallarin' ],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
   {
    nombre: "Pomarola2",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La noción de pomarola se emplea en el terreno de la gastronomía para aludir a una salsa elaborada a base de tomate. El término puede vincularse al vocablo italiano pomodoro, que se traduce justamente como “tomate”.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/pomarola_aipazt.png",
    marca: "",
    tags: ['rojo', 'tallarin' ],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Rabanitos",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El rábano es una raíz comestible originaria de Asia occidental y domesticada en la región mediterránea en la época de la Antigua Roma. Dada la variedad de subespecies existentes, se pueden consumir rábanos todo el año, cada una en su estación, la primavera y el verano por ejemplo, nos permite disfrutar del rábano rojo o rabanito, característico por su pequeño tamaño, pudiendo ser redondo, ovalado, cilíndrico o alargado, con la piel roja o rosada y su carne blanca",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/pepino_qr2atj.png",
    marca: "",
    tags: ['rojito', 'rabanito'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Sandilla",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La sandía es un fruto grande y de forma más o menos esférica que suele consumirse cruda como postre. Su pulpa es de color rojizo o amarillento y de sabor dulce.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/SANDIA_zb3sn4.png",
    marca: "",
    tags: ['rojo', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0  },
      { peso: 500, precio:  2.5 },
      { peso: 250, precio: 1.3  }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Tomate",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Aunque botánicamente el tomate es una fruta, sin embargo a efectos culinarios se le considera una hortaliza.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/tomate_yb7gps.png",
    marca: "",
    tags: ['rojo', 'tallarin'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Uva roja",
    tipoVenta: "UNIDADES",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "Pisum sativum es una planta herbácea de la familia de las leguminosas, más o menos trepadora, propia de la cuenca mediterránea, aunque muy extendida en todo el mundo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/uva_uj0vtx.png",
    marca: "",
    tags: ['rojo', 'uva', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Vainita",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "Las vainas o legumbres corresponden a frutos, los cuales están compuestos por ... además posiciones florales en que no hay vainas producto de la absición.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373216/productos/recorte%20200/vainita_kwa91n.png",
    marca: "",
    tags: ['verde', 'arroz con pollo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },

  {
    nombre: "Wantan",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "ABARROTES" },
    descripcion: "La masa o pasta Wonton, también llamada Wanton o Wantan, es una especialidad de la gastronomía china compuesta por agua, harina y sal.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373220/productos/recorte%20200/pomarola_aipazt.png",
    marca: "",
    tags: ['rojo', 'tallarin' ],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3 }
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Papa peruanita",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La papa es una planta herbácea. Su hábito de crecimiento varía entre las especies y dentro de cada especie. Cuando todas las hojas (o casi todas) se encuentran cerca de la base o en la base de tallos cortos, y están cerca del suelo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/papa_peruanita_uup5nb.png",
    marca: "",
    tags: ['papa', 'tuberculo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Papa blanca",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "La papa es una planta herbácea. Su hábito de crecimiento varía entre las especies y dentro de cada especie. Cuando todas las hojas (o casi todas) se encuentran cerca de la base o en la base de tallos cortos, y están cerca del suelo",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373219/productos/recorte%20200/papa_blanca_ttjoo3.png",
    marca: "",
    tags: ['papa', 'tuberculo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Maracuya",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "Esta fruta es una buena fuente de provitamina A, vitamina C y minerales como potasio, fósforo y magnesio. La vitamina A es esencial para la piel, el cabello, las mucosas, los huesos, la visión y el sistema inmunológico.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373218/productos/recorte%20200/maracuya_zov2k0.png",
    marca: "",
    tags: ['amarillo', 'fruta'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Manzana chilena'",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "FRUTAS" },
    descripcion: "La manzana es el fruto comestible de la especie Malus domestica, el manzano común. Es una fruta pomácea de forma redonda y sabor muy dulce, dependiendo de la variedad. % de la cantidad diaria recomendada para adultos. Fuente: Manzana en la base de datos de nutrientes de USDA.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373218/productos/recorte%20200/manzana_chilena_asyttu.png",
    marca: "",
    tags: ['rojo', 'manzana'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Zapallo loche",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El zapallo de verano es una excelente fuente de manganeso y vitamina C, también de magnesio, vitamina A (por su concentración de carotenos, beta caroteno incluido), fibra, potasio, folate, cobre, riboflavina, fósforo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/zapallo_loche_ixpp9r.png",
    marca: "",
    tags: ['amarillo', 'zapallo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
  {
    nombre: "Zapallo macre",
    tipoVenta: "KILOGRAMOS",
    envoltorio: "BOLSAS", 
    unidades: 10, 
    cantidadPorUnidad: 15, 
    precioCompra: 85,   
    precioVenta: 95, 
    alertaCantidad: 15, 
    sobrante: 14,
    categoria: { nombre: "VEGETALES" },
    descripcion: "El zapallo de verano es una excelente fuente de manganeso y vitamina C, también de magnesio, vitamina A (por su concentración de carotenos, beta caroteno incluido), fibra, potasio, folate, cobre, riboflavina, fósforo.",
    estados: "CON_STOCK",
    imagen: "https://res.cloudinary.com/dwkfj5sxb/image/upload/v1652373217/productos/recorte%20200/zapallo_macre_mr6dml.png",
    marca: "",
    tags: ['verde', 'arroz con pollo'],
    visibilidad: true,
    precios: [
      { peso: 1000, precio: 5.0 },
      { peso: 500, precio: 2.5 },
      { peso: 250, precio: 1.3}
    ],
    precioUnidad: 5.0
  },
];